version: '3.8'

services:
  web:
    image: "${DOCKER_IMAGE}:${DOCKER_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTAPI_PORT
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16.0
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pg_client:
    image: postgres:16.0
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./scripts/create_test_db.sh:/create_test_db.sh
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
