name: Tests

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Login to GitHub with gh CLI
          gh auth login --with-token <<< "$GH_TOKEN"

          # Create .env file from GitHub secrets
          source scripts/create_env_from_secrets.sh

          # Run tests
          source scripts/test.sh
