name: Test

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Testing
        run: |
          cd $GITHUB_WORKSPACE
          source scripts/test.sh
